### ISSUE TITLE
Tablet Mode Script has an error

### ISSUE THREAD

**Issue by klundry** [keenerd/c100p-tweaks#1]
When I run the c100p.tablet-mode.c script I get the following error.

./c100p.tablet-mode.c: line 9: //: Is a directory
./c100p.tablet-mode.c: line 10: //: Is a directory
./c100p.tablet-mode.c: line 16: //: Is a directory
./c100p.tablet-mode.c: line 22: //: Is a directory
./c100p.tablet-mode.c: line 25: /bin: Is a directory
./c100p.tablet-mode.c: line 26: z: command not found
./c100p.tablet-mode.c: line 27: syntax error near unexpected token `('
./c100p.tablet-mode.c: line 27:`    y is parallel to the hinge (useless here)'

**Comment by keenerd** [comment]
It is C code, not a script.  As noted in the top of the file, build with

```
gcc -O2 -lm c100p.tablet-mode.c -o c100p.tablet-mode
```

This information has also been placed in the repo readme.
