### ISSUE TITLE
Input configuration

### ISSUE THREAD

**Issue by shurik** [keenerd/c100p-tweaks#2]
Hi there,

Thanks for the helpful repo and all the scripts. I got my C100P to display SDDM login screen and I'm able to use the touchscreen and trackpad to move the cursor, but it doesn't seem to register clicks or touch on buttons. I'm using libinput.

Any hints around that issue?

**Comment by keenerd** [comment]
Sorry, no idea.  That just worked for me.

**Comment by shurik** [comment]
Thanks for getting back to me!
